export default function head() {
  return (
    <>
      <title>Jordi</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/app/jordi.ico" />
    </>
  )
}
