import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const header = ( 
    <header>
      <div>
        <h1>Jordi</h1>
        <p>Welcome to my place</p>
      </div>
    </header>
  );
  
  return (
    <html lang="en">
      <body>{children}{header}</body>
    </html>
  );
}
