import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const header = ( 
    <header>
      <div>
        <Link href="/">
        <h1>Jordi</h1>
        </Link>
        <p>Welcome to my place</p>
      </div>
    </header>
  );

  return (
    <html lang="en">
      <body>{header}{children}</body>
    </html>
  );
}
